### ISSUE TITLE
Performance comparison

### ISSUE THREAD

**Issue by ccorcos** [rusthon/Rusthon#14]
This is a really cool project -- way to go! I'm sure it wasn't a trivial amount of work. 

I'm curious what benefits or performance improvements Rusthon has over python. Have you run any benchmarks?

**Comment by hartsantler** [comment]
I'm updating the benchmarks now, starting with Pystone.  After that I will work on Richards, nbody and Fannkuch.  It will be benched against CPython and PyPy.

**Comment by hartsantler** [comment]
First benchmark:
http://rusthon-lang.blogspot.com/2015/02/rusthon-c11-backend.html

**Comment by hartsantler** [comment]
http://rusthon-lang.blogspot.com/2015/09/first-benchmarks.html

http://rusthon-lang.blogspot.com/2015/09/benchmarks2.html

**Comment by hartsantler** [comment]
http://rusthon-lang.blogspot.com/2015/09/pystone-benchmark.html

http://rusthon-lang.blogspot.com/2015/09/nbody-4x-faster-than-pypy.html

http://rusthon-lang.blogspot.com/2015/09/operator-overloading-benchmark.html

http://rusthon-lang.blogspot.com/2015/09/functor-benchmark.html
