### ISSUE TITLE
General overview of code

### ISSUE THREAD

**Issue by jmanuel1** [rusthon/Rusthon#16]
Hi! I was just wondering if there's anything to introduce to the code, such as an overview of the general structure, etc. Thanks!

**Comment by kud1ing** [comment]
I suggest to put this information either in the README.md or in the Wiki so that's easier to find for interested contributors.

**Comment by hartsantler** [comment]
all of the code in `pythonjs` folder is now deprecated, all the python source files in there have moved to `src` and converted into markdown format.  refactoring and documenting now.
