### ISSUE TITLE
Compiler and Interpreters

### ISSUE THREAD

**Issue by jcrubino** [rusthon/Rusthon#24]
Pythonjs should run "which x" x being the compiler or interpreter needed per language supported for better portability on posix systems.  

The translator could run this once on the first run and keep the information in a local config file for future reference.

**Comment by hartsantler** [comment]
I agree, the paths are hardcoded now, which is not good.  
I would like to avoid config files, and instead let `which x` run everytime; and for the case where the user wants to use some version of some compiler, we can add an options like this.
```
./rusthon.py --rustc=/path/to/my/rustc --go=/path/to/my/go
```

**Comment by jcrubino** [comment]
Will do.

**Comment by hartsantler** [comment]
closing this issue because we have good fallbacks for hard coded paths in rusthon.py, and everything is working well on both linux and osx.
