### ISSUE TITLE
c++ fix named parameters

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#29]
https://github.com/rusthon/Rusthon/blob/master/regtests/c%2B%2B/named_params.py

The tests I have been running so far on rust and c++ only use a single named parameter like this:
```python
def F( a=1 ): pass
F( a=100 )
```
Because the kwargs hack works well in JavaScript and Go, I had mistakenly assumed this was going to work with multiple named params with the rust and c++ backends.  I was wrong, it breaks in rust because a struct must have all members initialized, it breaks in c++ because a struct must be initalized with members in order and must be non-trival, g++ fails with this error: `sorry, unimplemented: non-trivial designated initializers not supported`

http://stackoverflow.com/questions/18731707/why-does-c11-not-support-designated-initializer-list-as-c99
http://stackoverflow.com/questions/203667/c-named-parameter-idiom-vs-boostparameter-library
http://justinvh.blogspot.com/2012/10/c11-named-parameters-using-operator.html

**Comment by hartsantler** [comment]
After taking a close look at the three solutions above: Named Param Idiom, Boost Param Lib, and Justin's operator suffixes hack; none of these are satisfactory.

This might work, a new class `KWargs` that has methods generated for all the keyword names, with all methods returning a pointer to `this`.  This way we can use the named param idiom style, but inside the call, rather than outside.
```c++
somefunc( x,y, (new KWargs()).foo(w).bar(u) )
```
Above `x` and `y` are normal positional arguments, `.foo(w)` and `.bar(u)` are the named parameters.

In KWargs the foo and bar methods do the same hackery as we used before, setting `__use__foo` and `__use__bar` to true.

**Comment by Shoozza** [comment]
Why not generate positional parameters for c++ with default values instead?

**Comment by hartsantler** [comment]
@Shoozza we need a way so that the user can call the function with named params out of order, just like they would in regular python where both calls below are the same:
```python
myfunc( x=1, y=2 )
myfunc( y=2, x=1 )
```

**Comment by Shoozza** [comment]
What I meant was to generate
```c++
myfunc(1, 2);
myfunc(1, 2);
```
in c++ for both cases.
(Reorder arguments automatically for the output)

**Comment by hartsantler** [comment]
Reordering the arguments automatically is a good optimization for the future.  It is easy to do for functions, because Rusthon knows about the function and its parameter order.  

But it breaks down when we have methods, callbacks, and other cases where Rusthon is not sure what you are calling.  Where it is unknown, the fallback case is going to be something like `myfunc( (new KWargs()).x(a).y(b).z(c) );`, unless we can think of something better.

**Comment by hartsantler** [comment]
I refactored the code to use the new style, but getting this error from g++.  What did i miss?
```
/tmp/regtest-named_params.py.cpp:20:4: error: ISO C++ forbids declaration of ‘_KwArgs_’ with no type [-fpermissive]
/tmp/regtest-named_params.py.cpp:20:4: error: expected ‘;’ at end of member declaration
/tmp/regtest-named_params.py.cpp:20:20: error: ISO C++ forbids declaration of ‘a’ with no type [-fpermissive]
/tmp/regtest-named_params.py.cpp:25:4: error: ISO C++ forbids declaration of ‘_KwArgs_’ with no type [-fpermissive]
/tmp/regtest-named_params.py.cpp:25:4: error: expected ‘;’ at end of member declaration
/tmp/regtest-named_params.py.cpp:25:4: error: redeclaration of ‘int* _KwArgs_::_KwArgs_’
/tmp/regtest-named_params.py.cpp:20:4: note: previous declaration ‘int* _KwArgs_::_KwArgs_’
/tmp/regtest-named_params.py.cpp:25:20: error: ISO C++ forbids declaration of ‘b’ with no type [-fpermissive]
/tmp/regtest-named_params.py.cpp: In member function ‘int _KwArgs_::a(int)’:
/tmp/regtest-named_params.py.cpp:23:11: error: cannot convert ‘_KwArgs_’ to ‘int’ in return
/tmp/regtest-named_params.py.cpp: In member function ‘int _KwArgs_::b(int)’:
/tmp/regtest-named_params.py.cpp:28:11: error: cannot convert ‘_KwArgs_’ to ‘int’ in return
/tmp/regtest-named_params.py.cpp: At global scope:
/tmp/regtest-named_params.py.cpp:88:19: error: expected primary-expression before ‘__kwargs’
/tmp/regtest-named_params.py.cpp:88:29: error: expected ‘,’ or ‘;’ before ‘{’ token
```

**Comment by Shoozza** [comment]
Should work now.
