### ISSUE TITLE
Support for document strings

### ISSUE THREAD

**Issue by kud1ing** [rusthon/Rusthon#34]
I think it would be nice if the Rusthon document strings would be preserved as documentation in the generated code.

**Comment by hartsantler** [comment]
I agree, i'll add it right now

**Comment by hartsantler** [comment]
https://github.com/rusthon/Rusthon/blob/master/examples/doxygen.md

**Comment by kud1ing** [comment]
Nice, thanks.

One nit:
```
    """
    Foo
    """
```
ends up n C++ as:
```
/**
*
*    Foo
*    
*/
```
while i think
```
/**
 *    Foo
 */
```
would be nicer.

**Comment by hartsantler** [comment]
I agree, it looks nicer like that.  I just threw this logic in, and there is room for improvement.  It would be better when looping over the lines, if the first line is blank skip it, and same for the last line.

**Comment by Shoozza** [comment]
Added first and last blank line skipping and the star positioning.

Comment indentation needs some work though (\t is tab):

```rusthon
\t'''
\t@param test  description
\t             continued description
\t'''
```
will output:
```c++
/**
 *\t@param test  description
 *\t             continued description
 */
```
instead of:
```c++
/**
 * @param test  description
 *              continued description
 */
```

**Comment by kud1ing** [comment]
Nice, thanks.

**Comment by kud1ing** [comment]
We could generally `strip()` the comment lines.

**Comment by Shoozza** [comment]
I had lstrip() in my first version but any strip() call would break the indentation of the "continued description" line

**Comment by kud1ing** [comment]
True. Another approach is to get the indentation of the first real comment line (in this case "\t") and substract that from the beginning of every comment line.

Something along the line of
```
numberof_whitespaces = len(first_line) - len(first_line.lstrip())
line_without_namespaces = line[numberof_whitespaces:]
```
Including checks whethere the first characters are indeed whitespaces.

**Comment by kud1ing** [comment]
This is implemented in https://github.com/rusthon/Rusthon/pull/39
