### ISSUE TITLE
Plans regarding "Python.js", "pythonjs/", Empythoned etc.?

### ISSUE THREAD

**Issue by kud1ing** [rusthon/Rusthon#42]
What are the plans regarding the original Python.js code and naming?
Will it go? Will it be renamed?

**Comment by hartsantler** [comment]
The pythonjs folder and most of the files in there are likely going to stay as they are named now.  Together along with the Empythoned scripts they make up the nodejs NPM package, which hasn't been updated in a long time, and should be.

**Comment by hartsantler** [comment]
the refactoring plan is likely going to be rewrite rusthon in markdown, basically just moving all the code now in .py files into a few markdown files, and then a script to recompile rusthon.py

**Comment by hartsantler** [comment]
starting now on refactoring into markdown, closing this question.
