### ISSUE TITLE
Use Travis CI

### ISSUE THREAD

**Issue by Shoozza** [rusthon/Rusthon#43]
We could probably use [Travis CI](http://travis-ci.org) to run the regtests and add a button for successful builds to the readme.
What do you think?

**Comment by hartsantler** [comment]
for sure man. i've never setup Travis CI, so if you have, feel free to go ahead and do it.

**Comment by hartsantler** [comment]
I setup Travis, but the build is failing, but works fine when i run locally.
https://github.com/rusthon/Rusthon/commit/504cbb4a5368e729ea94194f5a84c75af174d5c1

**Comment by hartsantler** [comment]
Travis error:
```
g++ -O3 -fprofile-generate -march=native -mtune=native /tmp/rusthon-c++-build.cpp -o /tmp/rusthon-c++-bin -pthread -std=c++11
cc1plus: error: unrecognized command line option ‘-std=c++11’
```
did that option get deprecated in g++?

**Comment by hartsantler** [comment]
looks like travis is way back at gcc4.6.
http://gearchicken.com/wordpress/?p=105
