### ISSUE TITLE
hello_angular.md: OSX - Error loading Adobe Unit Types

### ISSUE THREAD

**Issue by vasudeva-chaynes** [rusthon/Rusthon#55]
home:~/DD/Rusthon 532# python rusthon.py ./examples/hello_angular.md
2015-03-05 10:19:35.621 osascript[19294:d07] Error loading /Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types:  dlopen(/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types, 262): no suitable image found.  Did find:
	/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS/Adobe Unit Types: no matching architecture in universal wrapper
osascript: OpenScripting.framework - scripting addition "/Library/ScriptingAdditions/Adobe Unit Types.osax" declares no loadable handlers.
......
home:/Library/ScriptingAdditions/Adobe Unit Types.osax/Contents/MacOS 543# file *
Adobe Unit Types: Mach-O universal binary with 2 architectures
Adobe Unit Types (for architecture ppc):	Mach-O bundle ppc
Adobe Unit Types (for architecture i386):	Mach-O bundle i386

**Comment by hartsantler** [comment]
this could be an error from the browser being called with `webbrowser.open`.  for testing rusthon will open the webpage.  This error is confusing because there is nothing in the example that has anything to do with Abobe unit types.

**Comment by vasudeva-chaynes** [comment]
Yes, the problem was in the "webbrowser.open(tmp)" line. Googled sources indicate this is a problem with an Adobe update providing a 32 bit file while Mac OS wants a 64 bit file. The fix:
https://helpx.adobe.com/photoshop/kb/unit-type-conversion-error-applescript.html2

The example now runs w/o error or any output. (Is that intended?) Adding --tar angular.tar produced a tar file that unpacked sensible when double-clicked. 

For some reason
home:~/DD/Rusthon 543# tar -x -f hello_angular.tar
tar: myscript.js: implausibly old time stamp 1969-12-31 19:00:00
tar: untitled.html: implausibly old time stamp 1969-12-31 19:00:00

home:~/DD/Rusthon 532# /usr/bin/tar --version
bsdtar 2.8.3 - libarchive 2.8.3
home:~/DD/Rusthon 532# /usr/bin/tar --version
bsdtar 2.8.3 - libarchive 2.8.3
home:~/DD/Rusthon 546# tar --version
tar (GNU tar) 1.16.1
...
Also
home:~/DD/Rusthon 532# /usr/bin/tar --version
bsdtar 2.8.3 - libarchive 2.8.3
home:~/DD/Rusthon 544# /usr/bin/tar -x -f hello_angular.tar
home:~/DD/Rusthon 545# 
Does nothing (fails to create a directory).

**Comment by hartsantler** [comment]
it works well on linux, opens the web browser for you and displays the page.  Maybe on OSX we need to do something different.

**Comment by vasudeva-chaynes** [comment]
After other fiddling I added the following just before line 1126 (webbrowser.open call):
                if sys.platform == 'darwin':
                    tmp = 'file://:/' + tmp
Doesn't make sense, and there's likely a better way, but rusthon.py now opens the new page in my default browser (Safari).

The tar file generation is still as reported above, which is a total mystery at this point.

Anyway, it's very good being able to use rusthon now.
