### ISSUE TITLE
Does it support Javascript->Python translation?

### ISSUE THREAD

**Issue by Meai** [rusthon/Rusthon#61]
I'm confused because on this project: https://github.com/PythonJS/PythonJS
it says "PythonJS development has moved to Rusthon 
https://github.com/rusthon/Rusthon" but there is no mention of Javascript anywhere on Rusthon. 

Is this a different project, did some features fall out? 
Can you tell what features/language combos are supported as of yet?

**Comment by hartsantler** [comment]
The Javascript backend in Rusthon is stable, and a continuation of the work I had started in PythonJS.
The docs and wiki should be updated to make this more clear.
You use it by selecting it in your markdown with a special comment at the top `#backend:javascript`
Take a look at the Angular example.
https://github.com/rusthon/Rusthon/blob/master/examples/hello_angular.md

**Comment by Meai** [comment]
This is very hard to understand, the markdown is a config file or a documentation file? Do I HAVE to put "@myscript" into the real source? Or #backend:javascript? or both? Or just into the markdown file? Or does the real source need to be copy pasted into the markdown file?

**Comment by hartsantler** [comment]
The syntax is `#backend:javascript` not `#backend:python`.  The translator converts python to javascript, not javascript to python.

I have added this simple hello world:
https://github.com/rusthon/Rusthon/blob/master/examples/hello_javascript.md

note that Rusthon is untested and completely unsupported on the Virus Operating System (aka. MS Windows).  Rusthon is tested on Linux, and OSX.

**Comment by Meai** [comment]
oh damn, if you notice the title of issue I was actually asking for javascript->python conversion. Anyway, thanks your help. (and that simple hell world still has full english sentences in it.. hard to separate doc from keyword)
