### ISSUE TITLE
Need to specify what user needs to supply more explicitly

### ISSUE THREAD

**Issue by techtonik** [rusthon/Rusthon#62]
The schematics is awesome. I think about how to better communicate the input that is coming from users. They don't just write Markdown, they write a mix of languages, right? Also, what is the data that they need to supply?

I'd separate user input preparation into separate area.

**Comment by hartsantler** [comment]
Yes, the user writes in multiple languages, markdown is just the container format.  I've tried to make it clear in the docs, perhaps we need a help page just for this topic.

**Comment by techtonik** [comment]
If I get to Inkscape today, I will try to propose an alternative.

**Comment by techtonik** [comment]
@hartsantler - have you seen that - https://github.com/ipython/ipython/wiki/IPython-kernels-for-other-languages ?

I wonder, how Rusthon can fit this infrastructure..

**Comment by hartsantler** [comment]
I haven't tried IPython yet, but looks like a big project to integrate it well.  I'm updating the docs now, and cleaning up the javascript backend.

**Comment by techtonik** [comment]
I mentioned the IPython to point to its architecture that has multiple backends as well. It may happen that Rusthon is a the same wheel.

**Comment by techtonik** [comment]
Why RusthonC++.svg linked in README.md is not in this repository? It seems to belong here.

What program did you use to draw diagrams? I can find such symbols in Inkscape. Did you draw them manually?

**Comment by techtonik** [comment]
https://jupyter.org/

**Comment by hartsantler** [comment]
I just used Google Docs drawing tool to make the diagrams.  The svg's are in the gh-pages branch of this repo, along with the rusthon.github.io source.

**Comment by hartsantler** [comment]
closing this issue because the updated README.md explains how the markdown file is a container for multiple languages.
