### ISSUE TITLE
webworkers support multiple cores

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#66]
the current implementation of `spawn` uses only a single webworker.  the builtin `spawn` can be extended so the user can give the cpu number.
```python
worker1 = spawn( someclass(), cpu=0 )
worker2 = spawn( someclass(), cpu=1 )
```

**Comment by v3ss0n** [comment]
That is some crazy shit you doing @hartsantler . I mean , Awesome.

So almost all of javascript functions are supported by now?
Another question , if i do not want to use Markdown but use  Python to transalate to JavaScript, is that possible?

**Comment by hartsantler** [comment]
@v3ss0n thanks

1. i am not sure which javascript functions you are referring to.  You simply call any javascript function directly, there are no wrappers.

2. you can use python files instead of markdown, i just updated this example and added some documentation at the top.
https://github.com/rusthon/Rusthon/blob/master/examples/helloworld.py

**Comment by v3ss0n** [comment]
I basically mean , everything javascript can do , can be done in pythonjs ?

2. Thats awesome , i was always thinking since Rusthon , Markdown Literate is only default way to do things.

**Comment by hartsantler** [comment]
1. yes, anything you can do in javascript can be done in pythonjs, pretty much in the same way that everything that you can do in CoffeeScript you could also do in javascript.  Both CoffeeScript and PythonJS are designed for clean and direct compilation to JavaScript.  To make it easy to port existing javascript to pythonjs, there is some extra syntax that helps with that, like the `new` keyword, and `switch` statement.  You can also use `$` as you would in javascript, so all of the following is valid code:
```python
def $():
   pass
$()
foo( $ )
$.bar()
```

2. it is perfectly fine to use python files instead of markdown, however i recommend you use markdown - because with markdown you can easily inline blocks of javascript and code a server backend, keeping it all in the same file.  The other bad thing about using python files, is that it gives you the impression that the file name should provide a namespace (as it does with regular python), but this is not the case with pythonjs (where all files are merged into the same namespace).

**Comment by v3ss0n** [comment]
If pythonjs already as capable as Coffeescript , its awesome already.

> but this is not the case with pythonjs (where all files are merged into the same namespace).
Hmm , i c , I think it is quite possible to add name spacing like qooxdoo UI framework , where it gives name spaces to javascript and compiles nicely.

https://github.com/qooxdoo/qooxdoo

I am also thinking to use Python in place for javascript for qooxdoo.

**Comment by v3ss0n** [comment]
I think you should advertise pythonjs's capabilities more. Or make a separate project , that way will attract many helpless python developer souls, who got forced down their throat to write javascript for web UI .

**Comment by hartsantler** [comment]
i was planning to write some proper documentation on https://readthedocs.org/ and make DEB and RPM packages before promoting the project.  and there is still some things to fix, like `@property` decorators, and a few other things broken in the js backend.

**Comment by hartsantler** [comment]
everything is working again with webworkers, except calling a plain function, before when only a single core was used this made perfect sense:
```go
res = <- somefunction()
```
but now that the user can spawn to multiple cores, it no longer makes sense, because which core should be used to call `somefunction`?  Since spawn is what creates a worker instance, should the instance be the only way to call the free function, through a user defined wrapper, or some special syntax?  How likely is it that a user will want to call a free function inside the webworker?  Those free function are most likely to be used as subroutines within the worker, and not to be called directly from the outside.

**Comment by hartsantler** [comment]
multicores now working
https://github.com/rusthon/Rusthon/commit/e8c90a653a3fd8239e56c5b9837756bb3a304228
