### ISSUE TITLE
remove Dart backend

### ISSUE THREAD

**Issue by hartsantler** [rusthon/Rusthon#75]
Dart had potential, but its interop with JS is weak, and nobody gives a fuck about Dart anymore.  The performance of some dart code translated to JS was good, but it screwed up human readability with its super aggressive in-lining.  If all browser vendors (mobile and desktop) had quickly adopted the Dart VM into their browsers, this could have been a different story.

For server side development, Rusthon already has the Go and C++ backends that are nearly stable.

**Comment by techtonik** [comment]
Harts, how about making some declarative language for describing AST transformations?
I mean in cases where it is possible?
This way it is possible to store tree transformations what are possible to do, and let people enhance them themselves.

**Comment by hartsantler** [comment]
the code base of Rusthon is written with as little magic as possible, there is only a little use of transforming AST nodes inplace, or generating new AST nodes dynamically.  Trying to keep the code as simple as possible, i wrote things in a direct manner, basically walking the AST graph, and generate new code when traversing the tree.  The logic for transformation is mostly just `if/else` branches depending on some options or state.  Therefore, a declarative AST transforming language is hard to integrate, and not really required anyways, because you have a simple python script controlling everything anyways.  

The `ast` module that Rusthon is built on top of is a really good API,  and using it is just a matter of reading greentreesnakes.
http://greentreesnakes.readthedocs.org/en/latest/

**Comment by techtonik** [comment]
Yea, I know how it works, but it would be nice to see some AST matcher that can walk down the tree and choose replacement from either pre-declared block or run a dynamic code on a subtree.

**Comment by hartsantler** [comment]
The AST matcher is a good idea, and would help to refactor the translator in the long run.  You can file an issue for this and i will mark it as an enhancement for the Rusthon2.0 milestone.

**Comment by techtonik** [comment]
Done. Expanded idea a bit again.

**Comment by v3ss0n** [comment]
I agree on removing Darts backend. I once tried it and really hated it , Especially the final js file that it produce is GIGANTIC . I can't understand why google engineers design such a failure.

Yes , time to Let it go :queue annoying Frozen music :
