### ISSUE TITLE
On python 2.7.x the usage looks funny

### ISSUE THREAD

**Issue by raff** [rusthon/Rusthon#84]
A few lines from the usage:

usage: ./rusthon.py [python files] [markdown files] [tar file] [--release] [--run=] [--data=]
		[tar file] is the optional name of the output tar that contains the build
()
		source files, transpiled source, and output binaries.
()
		--release generates optimized output without extra runtime checks
()

The () are because "print" is a statement in 2.7.x and a function in 3.x. If rusthon requires 3.x maybe a check for that would be helpful. If it doesn't, consider adding "from __future__ import print_function"

**Comment by hartsantler** [comment]
https://github.com/rusthon/Rusthon/commit/c6cf411774a22dd6ea096cbcc7fdd7d405a4155a
