### ISSUE TITLE
Instruction for python standard libraries

### ISSUE THREAD

**Issue by wolfv** [rusthon/Rusthon#85]
Hi, 

I was wondering how one could use standard libraries of python, such as `random` or `math`.

The js output currently is `require('math');`

Is there already an implemented standard library? Or some instructions on how to make this work.

Cheers,

Wolf

**Comment by hartsantler** [comment]
the python standard libraries are not implemented.

**Comment by hartsantler** [comment]
https://github.com/rusthon/Rusthon/issues/59
